import { Flag } from '@keira/shared/constants';

export const ALLOWABLE_RACES: Flag[] = [
  { bit: 0, name: '人类' },
  { bit: 1, name: '兽人' },
  { bit: 2, name: '矮人' },
  { bit: 3, name: '暗夜精灵' },
  { bit: 4, name: '亡灵' },
  { bit: 5, name: '牛头人' },
  { bit: 6, name: '侏儒' },
  { bit: 7, name: '巨魔' },
  { bit: 8, name: '地精' },
  { bit: 9, name: '血精灵' },
  { bit: 10, name: '德莱尼' },
  { bit: 11, name: '虚空精灵' },
  { bit: 12, name: '狐人' },
  { bit: 13, name: '高等精灵' },
  { bit: 14, name: '熊猫人' },
  { bit: 15, name: '狼人' },
  { bit: 16, name: '曼阿里·艾瑞达' },
  { bit: 17, name: '赞达拉巨魔' },
  { bit: 18, name: '光铸德莱尼' },
  { bit: 19, name: '联盟恶魔猎手' },
  { bit: 20, name: '部落恶魔猎手' },
];
